spring:
  application:
    name: TataSteelTest
  datasource:
    url: jdbc:postgresql://localhost:5432/test
    username: postgres
    password: Rishaved@24
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format-sql: true
      show-sql: true
      database: postgresql
      database-platform: org.hibernate.dialect.PostgreSQLDialect



